name: pharmacy_website
description: A pharmacy website Flutter web application.

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  google_fonts: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Add this line

flutter:
  uses-material-design: true
